/**
 * dsh-waker build: materialize the runtime package into pkg/ from src/ bodies.
 *
 *   pkg/lib/index.js        host entry  (ESM; default export = plugin object)
 *   pkg/client/client.js    client entry (window.__ModuleLoader__ factory face)
 *   pkg/bridge/bridge.cjs   bridge process script (copied from src/bridge.cjs)
 *
 * package.json is the single source of truth: `name`/`version` seed the
 * generated metadata comment headers, and `dsh.client` is the field the DSH
 * plugin loader actually consumes (no plugin.yaml — that was a non-loader
 * extra file this script used to parse).
 *
 * Zero dependencies: plain string concatenation of source bodies.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const read = (p) => readFileSync(join(root, p), 'utf8')

const manifest = JSON.parse(read('package.json'))

const hostBody = read('src/host-body.js').trim()
const clientBody = read('src/client-body.js').trim()

mkdirSync(join(root, 'pkg', 'lib'), { recursive: true })
mkdirSync(join(root, 'pkg', 'client'), { recursive: true })
mkdirSync(join(root, 'pkg', 'bridge'), { recursive: true })

// ── Host half ───────────────────────────────────────────────────────────────
// src/host-body.js is an async function BODY (dynamic-package convention:
// `return { inject, apply }`). Static packages export a plugin object whose
// apply receives the real ctx — wrap the body so the same code runs as-is.
const host = `/**
 * dsh-waker host entry (generated by scripts/build.mjs from src/host-body.js — do not edit).
 * Manifest: package.json (name=${manifest.name} version=${manifest.version})
 */
export const name = ${JSON.stringify(manifest.name)}

const body = async () => {
${hostBody}
}

export default await body()
`
writeFileSync(join(root, 'pkg', 'lib', 'index.js'), host)

// ── Client half ─────────────────────────────────────────────────────────────
// The static client runner materializes factory(require) exports; seed words
// (react, react-dom, cordis, ui-slots, ui-primitives) are the ONLY closure
// symbols — no styles service. The body must inject CSS via document.
const client = `/**
 * dsh-waker client entry (generated by scripts/build.mjs from src/client-body.js — do not edit).
 */
window.__ModuleLoader__.load({ id: ${JSON.stringify(manifest.name)}, factory: (require) => {
var module = { exports: {} };
var exports = module.exports;

const body = async () => {
${clientBody}
}

// ModuleLoader factories are synchronous; the plugin body is async — hand the
// runtime a self-binding object and fill in apply/inject when the body settles.
var ready = null;
var pluginShell = {
  get inject() { return ready && ready.inject; },
  set inject(v) { ready = Object.assign({}, ready, { inject: v }); },
  apply: function (ctx) {
    return Promise.resolve(ready ? ready.apply(ctx) : body().then(function (p) { ready = p; return p.apply(ctx); }));
  }
};
body().then(function (p) { ready = p; }).catch(function (e) { console.error('[dsh-waker] client init failed:', e); });

module.exports = pluginShell;
module.exports.default = pluginShell;
return module.exports;
} });
`
writeFileSync(join(root, 'pkg', 'client', 'client.js'), client)

// ── Bridge ───────────────────────────────────────────────────────────────────
copyFileSync(join(root, 'src', 'bridge.cjs'), join(root, 'pkg', 'bridge', 'bridge.cjs'))
// AI 卡片模板 schema(bridge 自建模板用,__dirname/../resource)
mkdirSync(join(root, 'pkg', 'resource'), { recursive: true })
copyFileSync(join(root, 'resource', 'waker-aicard-receipt.json'), join(root, 'pkg', 'resource', 'waker-aicard-receipt.json'))

// ── Avatar IO helper ────────────────────────────────────────────────────────
mkdirSync(join(root, 'pkg'), { recursive: true })
copyFileSync(join(root, 'src', 'avatar-io.cjs'), join(root, 'pkg', 'avatar-io.cjs'))

console.log('build ok: pkg/lib/index.js', host.length, 'B; pkg/client/client.js', client.length, 'B; pkg/bridge/bridge.cjs copied')
